embroider-build/ember-auto-import

lib/analyzer.js

This was only needed because of the point at which we used to hook into the build pipeline. Now we always see the original ES module sources.

drop amd analysis support

---

README.md
index.js
lib/bundler.js
lib/webpack.js
package.json
yarn.lock

This PR makes per-module bundling strategies pluggable, and switches the default strategy to webpack.
For the set of use cases I've tried, webpack has a lot less hiccups than Rollup, primarily because (1) it's configured out of the box to deal with more Node-isms, and (2) Rollup is based around ES modules as the lingua franca, which forces all code to be interpreted in strict mode, which tends to break the weird and wacky old libraries everybody is often importing into their apps.

Switch default bundler strategy to webpack and make bundlers pluggable

---

index.js

If you don't have a vendor folder, under some conditions `tree` will be undefined here and cause an exception.

fix for missing tree in some older ember-cli versions

---

package.json

`ember-auto-import` currently does not work correctly with [`ember-cli-typescript`](https://github.com/typed-ember/ember-cli-typescript) because it runs before `ember-cli-typescript` has compiled .ts files to .js. This PR forces `ember-auto-import` to run after `ember-cli-typescript` so  that the analyzer finds the compiled .js files in the tree.

Support ember-cli-typescript

---

ts/analyzer.ts

Fixes #36 by not leaving empty values in `this.paths`. Plus this tightens up the handling of modules with no imports (they should also get removed from this.paths when deleted, but should not invalidate the cache).

fix module deletion

---

ts/webpack.ts

hi  @ef4 : 
when we use this in window,  building is failed  : 
```
ERROR in ./tmp/ember_auto_import_webpack-staging_dir-EqQ18vBa.tmp/entry.js 10:136
Module parse failed: Bad character escape sequence (10:136)
You may need an appropriate loader to handle this file type.
|     window.define('numeral', [], function() { return require('E:\work\js\node_modules\numeral\numeral.js'); });
>     window.define('node-uuid', [], function() { return require('E:\work\js\node_modules\node-uuid\uuid.js'); });
```
so, i  pull this request for you  to fix the path problem .

fixing paths in Window OS

---

ts/analyzer.ts

Fixes #46. 
We were inadvertently stripping non-Javascript files from the trees we analyze.

preserve non-JS files in the preprocessed trees

---

README.md
test-apps/sample-direct/app/components/hello-world.js
test-apps/sample-direct/app/templates/components/hello-world.hbs
test-apps/sample-direct/ember-cli-build.js
test-apps/sample-direct/package.json
test-apps/sample-direct/tests/acceptance/basics-test.js
ts/package.ts
ts/splitter.ts

This adds module aliasing to ember-auto-import's configuration options. While this is already a feature in webpack config, we need to make decisions about dependencies before we ever hand off to webpack, so it's appropriate that this config (along with "exclude") belongs in ember-auto-import proper.
Closes #51.

Add alias option to config

---

ts/auto-import.ts

This allows easier debugging of the webpack build output for both app and test bundles.
When using:
```
BROCCOLI_DEBUG=ember-auto-import:* ember build
```
You will now see both the `DEBUG/ember-auto-import/preprocessor/input` files (which were previously available) and `DEBUG/ember-auto-import/vendor/output/` files.
---
This _should_ help isolate which packages are responsible for the issue in https://github.com/ef4/ember-auto-import/issues/58 (e.g. is webpack just emitting invalid values, is something later in the pipeline mucking up the sourcemap comment, etc...

Add debugging of output via broccoli-debug

---

.eslintrc.js
README.md
babel-plugin/index.js
babel-plugin/package.json
package.json
scripts/link-them.sh
test-apps/a-dependency/index.js
test-apps/a-dependency/package.json
test-apps/sample-direct/app/controllers/dynamic-import.js
test-apps/sample-direct/app/router.js
test-apps/sample-direct/app/routes/dynamic-import.js
test-apps/sample-direct/app/templates/application.hbs
test-apps/sample-direct/app/templates/dynamic-import.hbs
test-apps/sample-direct/app/templates/index.hbs
test-apps/sample-direct/ember-cli-build.js
test-apps/sample-direct/fastboot-tests/basic-fastboot-test.js
test-apps/sample-direct/package.json
test-apps/sample-direct/tests/acceptance/dynamic-import-test.js
ts/analyzer.ts
ts/auto-import.ts
ts/bundle-config.ts
ts/bundler.ts
ts/index.ts
ts/splitter.ts
ts/webpack.ts
yarn.lock

This is nearly complete. Remaining blockers:

Lazy loading via dynamic import

---

package.json
ts/auto-import.ts
ts/webpack.ts
yarn.lock

Previously, we would sometimes allow webpack output files to appear in your app's final build that were not actually needed there. Now we only emit the ones that are needed (for lazy loading).

cleaner public tree output

---

ts/auto-import.ts
ts/index.ts
ts/webpack.ts

We don't want broccoli-asset-rev to rename our lazy chunks, because the webpack runtime loader won't be able to find them, and they already have hashes in their names anyway.

automatically configure fingerprinting for prod

---

ts/webpack.ts

Right now we only set the public path if we have discovered some dynamic imports. But that isn't right -- even if all our own imports are static, some of _those_ packages may have dynamic imports. So we should always do public path discovery.
Closes #64.

always set public path

---

.travis.yml
README.md
ts/bundler.ts
ts/package.ts
ts/webpack.ts

Now instead of searching for a Javascript file whose name starts with "vendor", we just assume our own code is being synchronously loaded, which allows us to locate it relative to ourself.
In addition, this can now be overridden with a public option.

change public asset URL heuristic

---

.travis.yml
package.json
ts/auto-import.ts
ts/bundle-config.ts
ts/bundler.ts
ts/index.ts
ts/webpack.ts
yarn.lock

ember-cli as of 3.4-beta has introduced changes that make it impossible for us to nicely emit the built dependencies via our own vendor and public trees, because it now considers those as *inputs* to the trees that we analyze, causing a circle.
This is, IMO, an architectural mistake in ember-cli, because there is no _real_ data dependency circle. Rather, the true data-dependency graph is being lost due to the way all trees are being combined and then re-separated to create the packager hook.
So anyway, now we must monkey patch EmberApp instead. It's pretty non-invasive and the function we are patching has been stable for a long long time.
Closes #26.

Refactoring for compatibility with newer ember-cli

---

ts/bundler.ts

The test-support target is not present during production builds, so we need to skip trying to read it when it doesn't exist.
Fixes #91.

fix prod build regression

---

ts/bundler.ts

Using utf8 here breaks binary files like wasm.

Removes encoding when copying lazily downloaded assets

---

.npmignore
.vscode/launch.json
package.json
scripts/test.sh
ts/analyzer.ts
ts/auto-import.ts
ts/broccoli-append.ts
ts/bundle-config.ts
ts/tests/append-test.ts
yarn.lock

This deals with #105.
The goal here is to not need to predict which bundles exist in the app's build output. If a bundle exists and we have things to add to it, we will add them. If it doesn't, we don't worry about it. broccoli-concat cannot do that, or at least it cannot while maintaining the order invariants we need.

Smarter append

---

ts/analyzer.ts
ts/tests/analyzer-test.ts

This was a silly typo that escaped because I wasn't testing the analyzer in rebuild scenarios.
Now I am.

fix analyzer rebuilds

---

ts/broccoli-append.ts

TIL the default `localeCompare` doesn't do the same thing as `<`.
Closes #110.

match the sort semantics expected by FSTree

---

package.json

Extremely minor, but I noticed the release notes mentioned the implementation was changed in 0.2.0. I was just doing a peak under the hood to see if rollup was used anywhere and this seemed like the only leftover reference.

Swap package.json keyword rollup -> webpack

---

README.md
scripts/test.sh
test-apps/sample-direct/ember-cli-build.js
test-apps/sample-direct/lib/csp-switcher/index.js
test-apps/sample-direct/lib/csp-switcher/package.json
test-apps/sample-direct/package.json
ts/bundler.ts
ts/package.ts
ts/webpack.ts

Closes #50.
This provides a first-class option for supporting strict Content Security Policies that forbid `eval`, and it ensures that we are running tests in that mode so we don't accidentally slip in a dependency on `eval` in the future.

Strict CSP support

---

ts/webpack.ts

Sometimes an ember app might need to close over the build app and vendor
files in order to hide any ember globals from the browser's global
scope. If you have a third-party script running that tries to use
`window.require` or `window.define` in a way that's incompatible with
ember's `loader.js` implementation, for instance.
In those cases, `window.define` won't be there unless another script has
defined it, and regardless, `ember-auto-import` is interested in the
values that ember defines.
Using `eval` here allows us to get the values defined in scope (by ember),
but also prevents webpack from noticing that we're using `define` and
`require`, which would send webpack its own behavioral path of resolving
things for the build. One of those few times when `eval` is your friend.

get `define` and `require` from scope w/o alerting webpack

---

ts/webpack.ts

You can get a "define cannot be used indirect" exception if our noParse rule fails to match the little loader file we're using.
That can happen when your temp directory has a different realpath than what's passed to the webpack builder.

Bugfix: noparse test can fail

---

.vscode/launch.json
packages/ember-auto-import/ts/broccoli-append.ts
packages/ember-auto-import/ts/tests/append-test.ts

This fixes #166. We had test coverage that tries to cover this case but the test used simpler paths than the real build.

Fix missing rebuild content

---

.gitignore

chore: add `yarn-error.log` to `.gitignore`

---

README.md

Added specific example of when this might be needed as well as a default
value. When I encountered my chunk.js files not being loaded from `/assets`, but from `/` instead I read these docs, but the language here convinced me I should move on to something else. I'm not sure if telling the browser to async load the scripts is 'unusual' or not, but I hope this saves someone else some time.

Improved docs for publicAssetURL

---

packages/ember-auto-import/package.json
yarn.lock

Close 192. See comment for link to upstream npm bug:
https://github.com/ef4/ember-auto-import/issues/192#issuecomment-466471583

workaround upstream npm bug

---

README.md

Passing a file path to Babel makes it possible to parallelize the work that Babel does :)

README: Update "Dynamic Import" instructions to allow parallel Babel processing

---

packages/ember-auto-import/ts/auto-import.ts
packages/ember-auto-import/ts/broccoli-append.ts
packages/ember-auto-import/ts/bundle-config.ts
packages/ember-auto-import/ts/tests/append-test.ts

I took a stab at the most basic level of support for CSS. These changes make `ember-auto-import` bundle any CSS found in the webpack output, so by specifying a webpack config that collects CSS, e.g. [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin), we can include CSS in Ember's vendor.css.
My personal use case is integrating CKEditor5 into my build. Rather than using one of their pre-built packages, I want to build/customize my own, and consume their source packages using `ember-auto-import` to mimic the [webpack build](https://github.com/ckeditor/ckeditor5-build-inline/blob/master/webpack.config.js) they use to generate the pre-built packages. It appears to work seamlessly for the Javascript, but I need to do something like …

Bundle CSS files

---

packages/ember-auto-import/ts/webpack.ts

They're not particularly actionable most of the time, and different apps have different size budgets.

disable size hints by default

---

packages/ember-auto-import/ts/broccoli-append.ts
packages/ember-auto-import/ts/tests/append-test.ts

D'oh!
When concatenating CSS, we want to use just '\n' as a separator, rather than ';\n' because CSS doesn't use semi-colons outside of rules. So only use ';\n' when concatenating Javascript.

Fix CSS concat separator

---

README.md

We ran into this in the Ember Guides and Deprecation app after updating dependencies, and if someone yarn installed by accident (since we used an npm lockfile set to version 1.2)

README - add FAQ section for Webpack polyfills

---

README.md

Ember-cli-babel has the process for registering babel plugins worked out
for addons, adding a quick note here will save some pain in tracking
that information down.
Fixes #254

[DOC] Add dynamic import from addon instructions

---

.github/workflows/nodejs.yml

Fixes the following CI error:
> error npm-package-arg@8.0.1: The engine "node" is incompatible with this module. Expected version ">=10". Got "8.17.0"
https://github.com/ef4/ember-auto-import/pull/271/checks?check_run_id=518716456

Update node version to 12.x (latest LTS)

---

packages/ember-auto-import/ts/bundler.ts
packages/ember-auto-import/ts/package.ts

@ef4 
there are many chunk files in my project, so auto-import-fastboot file size is too large .
if we never use fastboot , so ignore fastboot is better . 
related issue: https://github.com/ef4/ember-auto-import/issues/150

optional output fastboot files

---

packages/ember-auto-import/package.json
yarn.lock

`@babel/preset-env` leverages two lists of plugins to determine what to _actually_ do for any given set of targets. The first list comes from the gathered browser compat data and lives in `@babel/compat-data`, and the second list is the actually known set of plugins that `@babel/preset-env` itself depends on. Additionally, `@babel/preset-env`'s dependency on `@babel/compat-data` is a `^` dependency very intentionally allowing SemVer drift (so you can get the latest set of known support for browsers).
Unfortunately, prior to `@babel/preset-env@7.8.7` it would take the list of plugins directly from `@babel/compat-data` and attempt to compile them. Due to the fact that `@babel/compat-data` can drift, you can end up in a situation where the list of plugins that are attempted include plugins …

Update minimum version of @babel/preset-env to 7.10.2.

---

packages/ember-auto-import/package.json
yarn.lock

We have been pinned to an older webpack for a while due to https://github.com/webpack/webpack/issues/8656, which is really an NPM bug that gets tickled by the particular set of deps that come into play with webpack 4.29.
But we can't stay pinned forever. The [npm bug](https://npm.community/t/packages-with-peerdependencies-are-incorrectly-hoisted/4794/13) is effectively wontfix because NPM gets peerDeps wrong at a really deep level.
Hopefully enough other deps have shifted by now that the bug doesn't manifest often.

upgrade webpack

---

packages/ember-auto-import/package.json
packages/sample-babel7/package.json
packages/sample-es-latest/package.json
packages/sample-noparse/package.json
packages/sample-skip-babel/package.json
packages/sample-typescript2/package.json
yarn.lock

Also needed to move Node support to 10, the oldest still maintained version.

upgrade ember-cli-babel to v7

---

packages/ember-auto-import/ts/bundler.ts

Like we do [here](https://github.com/ef4/ember-auto-import/blob/ab4cc5614bfb7b56e0649de917b3de8bc073461f/packages/ember-auto-import/ts/webpack.ts#L229-L242), we need to concatenate arrays here or addons and apps will overwrite each other's array configurations.
I'm not sure how best to write a test for this change, and would love some advice.

Fix merging addon webpack configs

---

packages/ember-auto-import/ts/analyzer.ts
packages/ember-auto-import/ts/auto-import.ts
packages/ember-auto-import/ts/bundle-config.ts
packages/ember-auto-import/ts/index.ts
packages/ember-auto-import/ts/splitter.ts
packages/ember-auto-import/ts/tests/analyzer-test.ts

Prior to these changes, we would decide what bundle a given file should end up in based on the modules relativePath that imported it. This worked generally for application level tests that import external packages, as well as for many addon-test-support imports.
Unfortunately, this relative path analysis falls down in addons that intentionally customize their `treeForAddonTestSupport` so that the `addon-test-support/` folder contents are available **without** the `addon-name/test-support` suffix. This is done by a number of testing only addons, but the largest offenders are `ember-qunit` and `@ember/test-helpers`.
This introduces a new (possibly undefined) value that can be passed into `preprocessJs` to specify the `treeType` being transpiled. ember-cli will update to pass this value by …

Infer bundle type (app vs test) by original tree if known.

---

packages/ember-auto-import/ts/analyzer.ts
packages/ember-auto-import/ts/bundle-config.ts

When introducing `bundleForTreeType` (in #329) I accidentally emitted an invalid bundle type (`test` vs the correct `tests`). This updates to the correct value, extracts a shared type (to confirm things stay in sync), and adds type assertions to ensure that all cases are handled in both `bundleEntrybundleEntrypoint` and `bundleForPath`.

Ensure `bundleForTreeType` returns the proper values.

---

packages/ember-auto-import/ts/webpack.ts

So they need to be IE11-safe.
Fix #335.

entrypoint files don't get transpiled

---

packages/ember-auto-import/ts/package.ts
packages/sample-direct/app/components/hello-world.js
packages/sample-direct/app/templates/components/hello-world.hbs
packages/sample-direct/tests/integration/components/hello-world-test.js

Webpack's [`resolve.alias`](https://webpack.js.org/configuration/resolve/#resolvealias) supports resolving prefix aliases.
```js
{
resolve: {
alias: {
'react-query': 'react-query/es'
}
}
}
```
For instance the above config translates all paths starting with `react-query`:
- `react-query` ➡️ `react-query/es` (exact match)
- `react-query/foo` ➡️ `react-query/es/foo` (prefix match)
- `react-query-devtools` ➡️ `react-query-devtools` (no match, unchanged)
`ember-auto-import`'s `alias` option only supports exact matches so far.
This PR tweaks the `aliasFor(name)` method to also perform prefix matches in addition to exact matches.

feat: resolve alias as prefix

---

packages/ember-auto-import/ts/webpack.ts

Newer versions of ember-cli-babel (>= 7.24.0) will allow folks to move to using the more standard `babel.config.js` (instead of the "magical" configuration that `ember-cli-babel` has done historically).
For example, as of `ember-cli-babel@7.24.0-beta.2` you can add the following:
```js
// babel.config.js
const { buildEmberPlugins } = require('ember-cli-babel');
module.exports = function (api) {
api.cache(true);
return {
presets: [
[
'@babel/preset-env',
{
targets: require('./config/targets'),
},
],
],
plugins: [...buildEmberPlugins(__dirname)],
};
};
```
Without the changes here, `babel-loader` runs `@babel/preset-env` twice (once with the config specified by ember-auto-import and once from the configuration in the `babel.config.js`), the `@babel/preset-env` that is configured by the host …

Ensure babel compilation ignores a `babel.config.js`

---

README.md
packages/ember-auto-import/package.json
packages/ember-auto-import/ts/bundler.ts
packages/ember-auto-import/ts/package.ts
packages/ember-auto-import/ts/webpack.ts

This lets you rebuild in development when editing an auto-imported package.

introduce watchDependencies option

---

packages/ember-auto-import/ts/bundle-config.ts

Towards https://github.com/ef4/ember-auto-import/issues/284
This regex is used to detect if an import is referencing the tests or addon-test-support folders.
As it stands it will match `my-package/test-support` but not `@scoped/my-package/test-support` which seems like an oversight.
I honestly don't fully understand the potential downstream consequences of this or how to test it, but it seems like a fairly uncontroversial fix. I took a look at the tests and they're a little hard to follow, (which is understandable given the nature of this library), happy to add one if you can point me in the right direction.

Update regex to work with scoped npm packages

---

packages/ember-auto-import/ts/package.ts
test-scenarios/static-import-test.ts

This reverts commit 90d1680324c9423d463de1de82e9e94688b57130.
We will still want to roll this feature out, but
- we can't do it in a minor release
- if we're going to make this change to follow webpack's `resolve.alias`, we should really implement all of `resolve.alias`, including the trailing `$` for exact matches.

Revert "feat: resolve alias as prefix"

---

packages/ember-auto-import/ts/package.ts
test-scenarios/merged-test.ts
test-scenarios/package.json

This fixes https://github.com/ef4/ember-auto-import/issues/349 by caching on the parent addon or app's own identity, as well as caching from the child.

Fix config duplication

---

package-lock.json
packages/ember-auto-import/package.json
packages/ember-auto-import/ts/webpack.ts

I refactored the embroider packages so that the few common things we want to share go into their own separate package, allowing us to depend on only that and not all of embroider/core.
This is testing against an alpha release of embroider and should wait to merge until we can update it to a stable release.

Pull in fewer deps

---

packages/ember-auto-import/ts/webpack.ts

I don't think anyone has ever found this message helpful:
> The code generator has deoptimised the styling of ... as it exceeds the max of 500KB.
As long as we provide a setting (as opposed to leaving it in auto), babel won't emit the warning.

silence babel's unhelpful warning

---

CHANGELOG.md

Fix link to the guide "upgrade to version 2"

docs(CHANGELOG): fix link to guide upgrade to v2

---

package-lock.json
packages/ember-auto-import/package.json
packages/ember-auto-import/ts/analyzer.ts
packages/ember-auto-import/ts/tests/analyzer-test.ts

Prevents [type-only imports / exports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export) from ending up in the final bundle.
```ts
import type { compute } from 'heavy-library';
export async function performHeavyComputation(
...args: Parameters<typeof compute>
): Promise<ReturnType<typeof compute>> {
const { compute } = await import('heavy-library');
return compute(...args);
}
```

fix(analyzer): ignore type-only imports & exports

---

packages/ember-auto-import/ts/auto-import.ts
packages/ember-auto-import/ts/bundle-config.ts
packages/ember-auto-import/ts/bundler.ts
packages/ember-auto-import/ts/inserter.ts
packages/ember-auto-import/ts/package.ts
packages/ember-auto-import/ts/tests/inserter-test.ts
packages/ember-auto-import/ts/tests/splitter-test.ts
packages/ember-auto-import/ts/webpack.ts
test-scenarios/custom-html-test.ts

Allow the customization of inserted HTML via custom elements. Among other things, planning to fix #418, #420, #422, and #409 here.
Adds two new options:
```diff
export interface Options {
exclude?: string[];
alias?: { [fromName: string]: string };
webpack?: Configuration;
publicAssetURL?: string;
styleLoaderOptions?: Record<string, unknown>;
cssLoaderOptions?: Record<string, unknown>;
forbidEval?: boolean;
skipBabel?: { package: string; semverRange?: string }[];
watchDependencies?: (string | string[])[];
+ insertScriptsAt? string;
+ insertStylesAt?: string;
}
```
When unset, we keep today's behavior, which inserts your app scripts after `vendor.js`, app styles after `vendor.css`, test scripts after `test-support.js` and test styles after `test-support.css`.
When set, these are the names …

Support Customized HTML Insertion and Custom Entrypoints

---

package-lock.json
packages/ember-auto-import/package.json
packages/ember-auto-import/ts/analyzer.ts
packages/ember-auto-import/ts/tests/analyzer-test.ts

Backports #380 to [`v1.x`](https://github.com/ef4/ember-auto-import/tree/v1.x).

[v1.x] fix(analyzer): ignore type-only imports & exports

---

package-lock.json
packages/ember-auto-import/ts/analyzer-plugin.ts
packages/ember-auto-import/ts/analyzer.ts
packages/ember-auto-import/ts/auto-import.ts
packages/ember-auto-import/ts/index.ts
packages/ember-auto-import/ts/package.ts
packages/ember-auto-import/ts/tests/analyzer-test.ts
packages/ember-auto-import/ts/tests/splitter-test.ts
test-scenarios/indirect-test.ts
test-scenarios/package.json

The changes in #440 can break when an addon is using a 2.x copy of ember-auto-import that predates the changes. The problem is that older copies will run their own `included` hook which does not install the babel plugin.

mixing of old and new analyzer patterns

---

packages/ember-auto-import/ts/analyzer-syntax.ts
packages/ember-auto-import/ts/analyzer.ts

On Node <= 14, there seems to be a potential for EBADF to get raised
after a ReadStream has been closed (https://github.com/nodejs/node/issues/25335)
We can workaround this causing problems by finishing the deserializer's operations
rather than calling 'destroy' on the ReadStream mid-read. This way the Promise gets
resolved with the result before a potential EBADF can occur.
Then we can simply destroy the ReadStream explicitly when we know we're done with it.
Also made sure to add `emitClose` for Node 12, which is `false` by default until Node 14 and might be causing the close event handlers not to get processed. (Though TypeScript seemed upset about adding that, despite it being a documented option for `createReadStream`, so had to slap on a `// @ts-ignore`. Let me know if there's a way …

Avoid EBADF on ReadStream early close in Node 12

---

packages/ember-auto-import/ts/webpack.ts
packages/ember-auto-import/tsconfig.json
test-scenarios/webpack-config-test.ts

This is a fix for https://github.com/ef4/ember-auto-import/issues/412
Now we are merging externals correctly and using [combining-syntaxes](https://webpack.js.org/configuration/externals/#combining-syntaxes)

concat mixed configuration for webpack externals

---

test-scenarios/package.json

On the 1.x branch, tests aren't really testing the current version.
We have assertions about this on main, but this backports branch doesn't catch this problem.

fix test linkage

---

package-lock.json
packages/ember-auto-import/package.json
packages/ember-auto-import/ts/auto-import.ts
packages/ember-auto-import/ts/bundler.ts
packages/ember-auto-import/ts/inserter.ts
packages/ember-auto-import/ts/package.ts
packages/ember-auto-import/ts/webpack.ts

Under fastboot, CSS needs to always be in separate CSS files, not riding along inside the JS and being appended to the DOM by JS.
This is also a better production default, and that's what embroider does, so we're going to match the embroider behavior here and use separate CSS files in production builds.

fastboot css fixes

---

packages/ember-auto-import/ts/auto-import.ts

We already have code to defend our JS chunks from getting renamed by broccoli-asset-rev, but we need the same for any emitted CSS chunks.
Fixes #493.

don't let broccoli-asset-rev mess with css chunks

---

docs/upgrade-guide-2.0.md

Clarify the fact that, if you only use `ember-auto-import` as `devDependency` you are not forced to do a major release as a maintainer.

Clarify upgrade guide for addon

---

package-lock.json
test-scenarios/addon-dev-dep-test.ts
test-scenarios/common-chunk-test.ts
test-scenarios/conflict-test.ts
test-scenarios/csp-test.ts
test-scenarios/custom-html-test.ts
test-scenarios/customized-vendor-test.ts
test-scenarios/doubly-indirect-test.ts
test-scenarios/dynamic-import-test.ts
test-scenarios/ember-cli-typescript-2-test.ts
test-scenarios/ember-cli-typescript-3-test.ts
test-scenarios/ember-cli-typescript-4-test.ts
test-scenarios/fastboot-helper.ts
test-scenarios/import-sync-test.ts
test-scenarios/indirect-test.ts
test-scenarios/leader-test.ts
test-scenarios/merged-test.ts
test-scenarios/no-conflict-test.ts
test-scenarios/sample-addon-test.ts
test-scenarios/scenarios.ts
test-scenarios/skip-babel-test.ts
test-scenarios/static-import-test.ts
test-scenarios/targets-test.ts
test-scenarios/v2-addon-test.ts
test-scenarios/webpack-config-test.ts

We had a workaround that allowed us to use volta to independently control the node version per scenario. That doesn't work on current volta anymore, but now there is a `volta run` command that gives us the same effect without a hack.

Fix our usage of volta in the test suite

---

packages/ember-auto-import/ts/package.ts
packages/ember-auto-import/ts/tests/splitter-test.ts

Dummy apps have a logical root that is different from their package root.
Mostly we are tracking the app root so that package resolution knows when devDependencies are relevant (they're relevant in the app and nowhere else). The classic build glosses over this distinction. But embroider cares and treats the dummy app as a distinct package, so if you get the app root wrong it can seed the shared PackageCache with the wrong value and cause the dummy app to not see its own devDependencies.
I think this is source of failures in https://github.com/simplabs/qunit-dom/pull/1423

Adjust appRoot to account for dummy apps

---

packages/ember-auto-import/ts/webpack.ts

If users set webpack's devtool option, that should take priority over the default caused by our forbidEval option.

Prioritize user's devTool setting

---

packages/ember-auto-import/ts/auto-import.ts

avoids adding a duplicate analyzer-plugin to webpack on windows os
fixes an ERROR: Duplicate plugin/preset detected. 
Duplicated detected are:
"...node_modules\\ember-auto-import\\js\\analyzer-plugin.js",
"options": {
"MARKER": "eaimeta@70e063a35619d71f"
}, ...

use node path.join to build os specific file name

---

docs/upgrade-guide-2.0.md

Unfortunately, I missed this part as it looks very similar to `fingerprint.prepend`, but it really is important to not overlook the trailing `/assets` otherwise the url will be wrong. I wasted a couple hours with this and figured some others might miss that too. So probably a good reason to explicitly mention that.
Since I'm not a native speaker I would be happy if someone may give a better text suggestion

Improve upgrade-guide

---

package-lock.json
packages/addon-template/package.json
packages/app-template/package.json

Newer versions of ember-source use peerDependencies. But because they also depend on a babel plugin with an unsatisfied peerDep on `@babel/core`, scenario-tester and fixturify-project have no way of knowing that babel/core is needed at the top-level.
This works around the problem by having babel/core in the test apps.

Add babel/core to app templates

---

packages/ember-auto-import/ts/webpack.ts

As a compatibility feature, v2 addons are allowed to list externals in the package metadata. These are dependencies that should be resolved at runtime from the surrounding environment, not at build time. Embroider respects this option but ember-auto-import does not.

Respect v2 addon's explicit external list

---

packages/ember-auto-import/ts/splitter.ts
packages/ember-auto-import/ts/tests/splitter-test.ts
test-scenarios/import-sync-test.ts

This makes it so that you can do code like this: 
```js
import Route from '@ember/routing/route';
import { importSync } from '@embroider/macros';
export default Route.extend({
model() {
try {
return importSync(`/a-dependency/${42}`);
throw new Error('you should not reach this point');
} catch (err) {
return { message: err.message }
}
},
});
```
Without it breaking the build. 
This change sacrifices the clarity of the build time error for a slightly more correct implementation that allows for the above code 👍 
I discussed with @ef4 yesterday (on my Twitch live stream 😂 ) how we can bring a nicer runtime error to this scenario in the future but that will require a bit more work.

Move Dynamic Template Import error to runtime instead of a build error

---

packages/ember-auto-import/ts/webpack.ts
test-scenarios/node-es-modules.ts

Adds support for Ember addons that opt-in to node's ES module syntax via
type=module.
When writing to a directory whose package.json is controlled by a third
party, maximum compatibility is achieved by writing either `.cjs` or `.mjs`
files as appropriate, and not `.js` files.
If neither package is concerned with backwards compatibility, writing ES
modules into a `.js` file can be fine, but writing commonjs modules into
a `.js` file in a directory whose package.json is controlled by a third
party (e.g. another package) is not generally going to be
forwards-compatible.
See also https://github.com/ember-cli/ember-cli/pull/10053#issue-1412217269
Co-authored-by: Robert Jackson <rjackson@linkedin.com>

Add support for consumers using Node ES Module support (e.g. `type=module` in `package.json`)

---

packages/ember-auto-import/ts/package.ts

ember-auto-import is used for loading V2 addons. There is a bug, that babel-plugin-htmlbars-inline-precompile is always used. For newer versions of ember-source>=3.27.0 babel-plugin-ember-template-compilation should be used.
This PR can be the start of a discussion of how to solve it. If there is a suggestion on how to improve the solution, I would like to implement it.

added babel-plugin-ember-template-compilation

---

package-lock.json
packages/ember-auto-import/package.json
packages/ember-auto-import/ts/package.ts
test-scenarios/doubly-indirect-test.ts

We need to add `@babel/plugin-transform-class-static-block` and `@babel/plugin-proposal-private-methods` to the list of our plugins to correctly process the code with private properties and static blocks.

Support private properties and static blocks

---

.github/workflows/publish.yml
.github/workflows/release-plan-preview.yml
package-lock.json
package.json
packages/addon-template/package.json

This uses [release-plan](https://github.com/embroider-build/release-plan) which was originally developed for [embroider](https://github.com/embroider-build/embroider) and recently extracted into its own package.
This PR adds the workflows that create the Release PR and the publish step 👍

Add release-plan for automating releases

---

packages/ember-auto-import/ts/webpack.ts

With a config like `allowAppImports: ['images/**/*.webp']` and importing a file like `image.webp`, eai would fail to handle that import properly, as it assumes that explicit extensions would be 1-3 characters long.
With a proper webpack loader we can make it import any type of file, so we shouldn't make assumptions about the possible extensions.

Allow arbitrary extensions for app-imports

---

packages/ember-auto-import/ts/package.ts
packages/ember-auto-import/ts/util.ts
packages/ember-auto-import/ts/webpack.ts
test-scenarios/static-import-test.ts

With the new `allowAppImports` feature, apps can import resources that are handled with custom webpack loaders. Some can allow you to customize their behavior by passing query params, like `import image from './images/image.jpg?size=1024`.
This PR is fixing two related issues:
* make sure that an `allowAppImports` glob like `'images/**/*.jpg'` would also match for imports that include query params, by stripping the query part before trying to match the import to the glob
* query params could technically also include quotes. These already got escaped when building the app-chunk that has the AMD-shims, but the regex to replace `EAI_DISCOVERED_EXTERNALS` was not taking their possible existence into account correctly, leaving `EAI_DISCOVERED_EXTERNALS` around in the final build.

Fix imports with a query part

---

packages/ember-auto-import/ts/package.ts
test-scenarios/dynamic-import-test.ts

The `ember-auto-import/babel-plugin` is necessary for apps that want to add dynamic import support to their classically built code. But inside a file controlled by allowAppImports, webpack is doing the buildng and there is already dynamic import support, so using the plugin there is actually an error.

Fix dynamic import inside allowAppImports dirs

---

package-lock.json
packages/ember-auto-import/ts/webpack.ts
test-scenarios/leader-test.ts
test-scenarios/static-import-test.ts

The output produced by webpack's `asset/resource` and `asset/source` loaders is just a plain CJS module with no es compatibility built in. Since ember-auto-import turns the user's `import` into a `require()` in the entryfile, webpack doesn't have any reason to know to add cjs compatibility. This results in not getting a `default` export on the resulting module.
This change adds general es-compatibility checking to our `require()` calls. This is exactly the same as embroider already does.

Add es-compat to make asset loaders work as expected

---

package-lock.json
package.json

you can see in https://github.com/embroider-build/ember-auto-import/pull/621 that CI is currently failing because of a floating dependency on minimatch
this minimatch dependency floated because of the dependency chain ember-cli-babel@8 > babel-plugin-module-resolver@5 > glob@9 > minimatch@8
Edit: it turns out the original culprit is the fact that `@embroider/util` bumped the ember-cli-babel major version without doing a major themselves 😞 Looking at the full list of `npm why minimatch@8` you can see why: 
```
minimatch@8.0.4 dev
../../node_modules/@embroider/util/node_modules/minimatch
minimatch@"^8.0.2" from glob@9.3.5
../../node_modules/@embroider/util/node_modules/glob
glob@"^9.3.3" from babel-plugin-module-resolver@5.0.2
../../node_modules/@embroider/util/node_modules/babel-plugin-modu …
```

fix glob version on lts tests

---

packages/ember-auto-import/ts/bundle-config.ts
packages/ember-auto-import/ts/inserter.ts
packages/ember-auto-import/ts/webpack.ts
test-scenarios/layering-test.ts

Fixes https://github.com/embroider-build/ember-auto-import/issues/503
Closes https://github.com/embroider-build/ember-auto-import/pull/512

Improved layering between app and tests bundles

---

.github/workflows/nodejs.yml
test-scenarios/suite-setup-util.ts

This implementation is taken (almost) exactly from what embroider is doing here: https://github.com/embroider-build/embroider/blob/main/test-packages/support/suite-setup-util.ts
Note: I'm filtering the tests that are running on Windows so as not to massively inflate the CI runtime. This PR increases the number of jobs on CI from 122 to 155.

setup windows tests

---

packages/ember-auto-import/ts/package.ts

I noticed this when I was linking a package that had a peerDependency range wider than it's devDependencies (ember-showdown-prism)
i don't understand why we would ever want to check the requested range of a dev depdency of a package 🤔 but perhaps there is a nuance that I don't understand here and we need to encode that nuance into the question that is being asked

only check devDependencies when checking requested range of an app package

---

.github/workflows/plan-release.yml
.github/workflows/publish.yml

This fixes an issue where adding a label to a PR **from a fork** after it has been merged doesn't allow the release-plan job to run correctly
cc @simonihmig I noticed you had this exact issue with https://github.com/embroider-build/ember-auto-import/pull/623

update release-plan CI jobs

---

packages/ember-auto-import/package.json

I noticed this today while looking into an issue, but really I wanted to open a PR to prove that CI is currently failing for LTS

fix the repo link in the published package

---

package-lock.json
packages/ember-auto-import/ts/auto-import.ts
packages/ember-auto-import/ts/bundler.ts
types/broccoli-debug/index.d.ts

If you try to enable broccoli-debug these actually crash, because buildDebugCallback is really a static method that needs the correct `this`. This used to work, but something about the CJS-interop implementation changed at some point.

Fixing broccoli-debug

---

packages/ember-auto-import/ts/auto-import.ts
packages/ember-auto-import/ts/bundler.ts
packages/ember-auto-import/ts/package.ts
packages/ember-auto-import/ts/splitter.ts
packages/ember-auto-import/ts/tests/splitter-test.ts
packages/ember-auto-import/ts/webpack.ts
test-scenarios/v2-addon-test.ts

V2 addons are allowed to declare in their package.json that they offer `renamed-modules` for backward compatibility. For example, when we switch ember-source to publish as V2 [these names](https://github.com/emberjs/ember.js/blob/e1abff5ccd2fb747cdc53374936155d587740f72/package.json#L184) should be available directly through ember-auto-import.
Embroider uses `renamed-modules` extensively when auto-upgrading addons, but ember-auto-import doesn't support it yet. This PR will add it.

Renamed modules support

---

packages/ember-auto-import/ts/webpack.ts
pnpm-lock.yaml
test-scenarios/package.json
test-scenarios/smoke-test.ts

Fixes https://github.com/embroider-build/ember-auto-import/issues/665
You can see that I created a failing test in my first commit and then fixed that test in my second 👍 the only way to recreate this bug is to have an app where the only usage of `@glimmer/component` was coming from a v2 addon so we needed a new scenario that was essentially empty.

Fix missing @glimmer/component error
