embroider-build/ember-auto-import

lib/dep-finder.js, lib/splitter.js, test-apps/inner-lib2/deeper/index.js, test-apps/inner-lib2/deeper/named.js, test-apps/inner-lib2/index.js, test-apps/inner-lib2/named.js, test-apps/sample-addon/tests/unit/inner-module-test.js
=> support importing inner modules

package.json, ts/webpack.ts, yarn.lock
=> Fix string escaping when emitting intermediate Javascript

ts/analyzer.ts, ts/auto-import.ts, ts/bundler.ts, ts/splitter.ts, ts/webpack.ts
This takes a bunch of untyped things and makes them more understandable by the typescript compiler.
=> refactoring for better type checking

ts/webpack.ts
It was not correct to unlink the webpack build output, because in development we rely on having a persistent webpack that does incremental rebuilds, and it doesn't re-output the files we unlink.
=> fix rebuilds

package.json
=> Run auto-import after ember-cli-coffeescript

.travis.yml, scripts/change-ember-cli-version.sh, scripts/test.sh, test-apps/sample-direct/app/index.html, test-apps/sample-direct/ember-cli-build.js, test-apps/sample-direct/lib/.eslintrc.js, test-apps/sample-direct/lib/bundle-switcher/index.js, test-apps/sample-direct/lib/bundle-switcher/package.json, test-apps/sample-direct/package.json, test-apps/sample-direct/tests/index.html, ts/auto-import.ts, ts/bundle-config.ts, ts/bundler.ts, ts/index.ts, ts/splitter.ts, ts/webpack.ts
=> Fix support for customized outputPaths

package.json, ts/broccoli-append.ts, ts/source-map-url.ts, ts/tests/append-test.ts
This is at least a partial fix for #111.
=> Don't match non-trailing sourceMapURL

package.json, ts/bundler.ts, ts/tests/analyzer-test.ts, ts/tests/append-test.ts, ts/tests/tslint.json, ts/webpack.ts, types/broccoli-plugin/index.d.ts
=> put our webpack tempdirs under broccoli control

packages/ember-auto-import/ts/broccoli-append.ts, packages/sample-direct/ember-cli-build.js, packages/sample-direct/lib/bundle-switcher/index.js, packages/sample-direct/package.json, scripts/test.sh
=> Fix exception when using custom vendor JS path without any leading directory

packages/ember-auto-import/package.json, yarn.lock
https://www.npmjs.com/advisories/755
=> fix: change from security audit

CONTRIBUTING.md, README.md
See slides by @kennethlarsen from EmberConf 2019 at https://noti.st/kennethlarsen/jXt2dj/the-state-of-community-documentation#s9GVOpX
=> Updated the README with advice from @kennethlarsen

packages/ember-auto-import/ts/webpack.ts
Fixes https://github.com/ef4/ember-auto-import/issues/215
=> Add `node: false` to default webpack config

packages/ember-auto-import/package.json, yarn.lock
GitHub is flagging it as a security vulnerability, although we don't use it with untrusted input.
Fixes https://github.com/ef4/ember-auto-import/issues/229
=> upgrade handlebars

packages/ember-auto-import/package.json, yarn.lock
=> add missing dep

README.md
Solution for #251 
This PR adds couple of missing sections to the README that would fix
the above issue when used in an app or addon.
There is no code modification involved.
=> Solution for #251

packages/ember-auto-import/ts/webpack.ts
=> add [id] to the chunkname

packages/ember-auto-import/package.json, packages/ember-auto-import/tsconfig.json, yarn.lock
Should hopefully fix https://github.com/embroider-build/embroider/issues/509
=> Update @embroider/core dependency

packages/ember-auto-import/ts/bundler.ts, packages/ember-auto-import/ts/webpack.ts, test-scenarios/common-chunk-test.ts
=> Fixing common chunk bug

.github/workflows/nodejs.yml, package-lock.json, packages/app-template/package.json, packages/ember-auto-import/package.json, packages/ember-auto-import/ts/auto-import.ts, packages/ember-auto-import/ts/bundler.ts, packages/ember-auto-import/ts/package.ts, packages/ember-auto-import/ts/tests/splitter-test.ts, packages/ember-auto-import/ts/webpack.ts, test-scenarios/package.json, test-scenarios/targets-test.ts
Fixes https://github.com/ef4/ember-auto-import/pull/392
=> [beta] IE11 fix

packages/ember-auto-import/ts/package.ts
https://github.com/babel/ember-cli-babel/issues/401
=> stick with older ember-cli-babel API due to bug

packages/ember-auto-import/package.json, packages/ember-auto-import/ts/inserter.ts
And refactor the inserter to provide a safety check for this class of problem.
=> Run inserter before asset-rev

package-lock.json, test-scenarios/own-test.ts, test-scenarios/package.json
This is easy for forget during a release, so adding a test as well.
=> update self dep in test suite

docs/upgrade-guide-2.0.md
Could possibly be the cause of this issue (if people copy/pasta'd)?
https://github.com/getsentry/sentry-javascript/issues/3670
=> Fix publicAssetURL typo in v2 upgrade docs

package-lock.json, packages/ember-auto-import/ts/analyzer-plugin.ts, packages/ember-auto-import/ts/tests/analyzer-test.ts
=> Detect reexport all

package-lock.json, packages/ember-auto-import/ts/webpack.ts
=> windows symlinks->junctions

packages/ember-auto-import/ts/inserter.ts
=> avoid unnecssary full page reloads

packages/ember-auto-import/ts/bundler.ts
=> Allow user webpack config to override internal config
